### ISSUE TITLE
compatibility

### ISSUE THREAD

**Issue by ozdigennaro** [envylabs/faraday-detailed_logger#1]
What old versions of rails is this compatible with?
I'm using (unfortunately) rails 2, faraday 0.9.0

Thanks.
Oz

**Comment by nbibler** [comment]
It _should_ work with any version of Rails. It would be configured with something like:

```ruby
connection = Faraday.new(:url => "http://sushi.com") do |faraday|
  faraday.response :detailed_logger, Rails.logger
end
```

It only expects that the given logger follow the same interface as Ruby's Logger instances, I believe.
