### ISSUE TITLE
Logging output doesn't contain request body?

### ISSUE THREAD

**Issue by ttrmw** [envylabs/faraday-detailed_logger#5]
Hey,

When I make a request I appear to get output of the form:

```
INFO -- : #{method} #{request_url}
DEBUG -- : #{request_headers}\n#{response_body}
WARN -- : HTTP #{status}
D, [2017-04-18T14:06:31.864393 #6513] DEBUG -- : #{response_headers}\n#{response_body}
```
Whereas the docs suggest I should get the request body in that debug line, am I doing something wrong?

**Comment by nbibler** [comment]
DEBUG level logging _should_ be [outputting the response body](https://github.com/envylabs/faraday-detailed_logger/blob/7399d905d4862e5559ba2bf436846c3aed193162/lib/faraday/detailed_logger/middleware.rb#L79), yes.

I'm having a hard time understanding your question/example. Are you not seeing anything in your DEBUG output?

**Comment by ttrmw** [comment]
Hey,

It's been a while since I opened this issue so I can't really repro, or even remember it clearly 😁 Indeed, I think I moved on from using this gem in the end. I think the problem I had was that the docs suggest the DEBUG line should contain the /request/ body, rather than the /response/ body that is actually returned. 

IIRC my use case was debugging the request itself.

Cheers & kind regards

Thomas

**Comment by nbibler** [comment]
Ohh... I didn't catch the difference (`request` vs `response` in line 2) in the original ticket. I'll attempt to reproduce and see if I can find a reason for not seeing a request portion of the transaction. Thanks for getting back!

**Comment by nbibler** [comment]
I'm not seeing this as a problem in the tests or in production applications. I know you weren't able to reproduce because of the delay in my response... sorry about that.

Maybe I can try some combination of available versions of `faraday-detailed_logger` and `faraday` around the time you created the ticket (April 18, 2017) and see.

Otherwise… I'm not sure how else to try to get a similar behavior as what's reported.

**Comment by ttrmw** [comment]
No worries, it's not a problem for me any more, and if you can't repro then it's likely not a problem for anyone else, I'll close this issue 👍
